### ISSUE TITLE
Error in apply_all_projects()

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#65]
The scenario creation has an unexpected behavior. I think it is creating a Scenario object named Scenario that is confusing python. Please look at 'Broken Parallel Managed Lanes.ipynb' (just uploaded in a commit to develop). 

Note that the object my_scenario is a network_wrangler.Scenario.Scenario pointer.

I think this may be related to the issues we've seen with trying to reinstantiate a scenario without reloading the kernel. (There's a global Scenario object that objects to instances of the Scenario class?)

**Comment by e-lo** [comment]
@jhelsel11 can you add the broken managed lane project card? I think you have it in your wrangler directory?

**Comment by e-lo** [comment]
> my_scenario is a network_wrangler.Scenario.Scenario pointer

That should be the case, because one is the module (filename) and one is the class...however, the module really should be lower case (as it is in lasso)...so let me see if that clears things up.

**Comment by jhelsel11** [comment]
I'm having trouble connecting to the computer with the files on it, but will upload them later tonight. When it goes up, will you please check my syntax for the naming of the links I want to modify? At @DavidOry's suggetion, I've tried apply the project directly, but when I use ModelRoadwayNetwork.from_RoadwayNetwork(), it returns a network but says no managed lanes were detected.

**Comment by e-lo** [comment]
Just committed some changes so this is now:
`<network_wrangler.scenario.Scenario at 0x1064d9898>`

**Comment by e-lo** [comment]
>will upload them later tonight.

You could also just paste it as txt in the notebook if that ends up being easier.

**Comment by jhelsel11** [comment]
I don't have the file on my local computer at all. It's all on the remote.

**Comment by jhelsel11** [comment]
I've pushed the project cards to the network_wrangler branch.

**Comment by e-lo** [comment]
Thx. What is the different between working and broken?

**Comment by e-lo** [comment]
The issue is assigning a list-like item to multiple rows in the DataFrame which was recently broken/deprecated in Pandas and documented here (although still not sure what the solution is yet):

https://github.com/pandas-dev/pandas/issues/26333

**Comment by e-lo** [comment]
Assigning this to @kulshresthaa since he has an issue to do some fixing of this method anyway.

**Comment by e-lo** [comment]
(noting that really this is a wrangler issue, not lasso)

**Comment by jhelsel11** [comment]
Is the format of the identifiers correct? I only need the model_link_id and not the nodes?

**Comment by jhelsel11** [comment]
> Thx. What is the different between working and broken? (other than the obvious)
> 
> I replicated the error with "broken" and the error log has plenty to work with so I'll see what I can do.

There is no difference right now. I figured there was an even chance I had messed up the formatting so I wanted to have a different set of files with the "working_" tag.

**Comment by e-lo** [comment]
> Is the format of the identifiers correct? I only need the model_link_id and not the nodes?

As long as the link ID is a unique identifier you are fine. Here is the code that does the validation.


```python
selection_keys = [k for l in selection["link"] for k, v in l.items()]
        unique_link_id = bool(
            set(RoadwayNetwork.UNIQUE_MODEL_LINK_IDENTIFIERS).intersection(
                set(selection_keys)
            )
        )

        if not unique_link_id:
            for k, v in selection["A"].items():
                if (
                    k not in self.nodes_df.columns
                    and k != RoadwayNetwork.NODE_FOREIGN_KEY
                ):
                    err.append(
                        "{} specified in A node selection but not an attribute in network\n".format(
                            k
                        )
                    )
            for k, v in selection["B"].items():
                if (
                    k not in self.nodes_df.columns
                    and k != RoadwayNetwork.NODE_FOREIGN_KEY
                ):
                    err.append(
                        "{} specified in B node selection but not an attribute in network\n".format(
                            k
                        )
                    )
```

**Comment by kulshresthaa** [comment]
Yes, Looks like the issue is with setting the list/dict type object columns of dataframe. 

The solution I found is that in such cases the column needs to be first converted to object type. 

Instead of this:
`self.links_df.loc[link_idx, attribute] = attr_value`

We need something like:
```
if attribute in self.links_df.columns and not isinstance(attr_value, numbers.Number):
    # if the attribute already exists
    # and the attr_value we are trying to set is not numeric
    # then change the attribute type to object
    self.links_df[attribute] = self.links_df[attribute].astype(object)

if attribute not in self.links_df.columns:
    # if it is a new attribute then initiate with NaN values (object type)
    self.links_df[attribute] = "NaN"

# even after setting object type to the attribute column, only setting one row at a time works. not sure why that is!
for idx in link_idx:
    self.links_df.at[idx, attribute] = attr_value
```

Not an elegant solution but seem to work. 

Made the code change and pushed to wrangler ([commit](https://github.com/wsp-sag/network_wrangler/commit/f764a0504bbf7cb2f5940fd126bc488ca49414ff)). @jhelsel11 can you test with the new wrangler code?

**Comment by jhelsel11** [comment]
I think we can close this issue.
