### ISSUE TITLE
Project Card Creation Failing because of a crs error

### ISSUE THREAD

**Issue by jhelsel11** [wsp-sag/Lasso#78]
Rachel attempted to create a project card yesterday and ran into issues reading the area type shape file. It's saying that there is no crs or epsg in the shape file. Do either of you know why that might be happening? Could it be related to the log file instead of the shape file?

[Test1 - Jupyter Notebook error 2.pdf](https://github.com/wsp-sag/Lasso/files/4723769/Test1.-.Jupyter.Notebook.error.2.pdf)
[Test1 - Jupyter Notebook error.pdf](https://github.com/wsp-sag/Lasso/files/4723771/Test1.-.Jupyter.Notebook.error.pdf)

**Comment by kulshresthaa** [comment]
resolved?

**Comment by jhelsel11** [comment]
I think so. After looking at Rachel's computer, I think she was in the Master branch, which has not been updated with the epsg fix.

**Comment by jhelsel11** [comment]
[Test1 - Jupyter Notebook error 3.pdf](https://github.com/wsp-sag/Lasso/files/4724417/Test1.-.Jupyter.Notebook.error.3.pdf)
I was wrong. She's still having an issue. I'm going to try to walk through with her on the st paul network instead of the full network and see if I can iterate more quickly.

**Comment by i-am-sijia** [comment]
@jhelsel11 can we recreate the error in house?

**Comment by jhelsel11** [comment]
Not at the moment. I was able to create a project card using her log file on Daffy. I will likely recommend that she reinstalls lasso from scratch if the error persists.

**Comment by jhelsel11** [comment]
@i-am-sijia suggested checking the geopandas dependencies. I am doing that with Rachel now.

**Comment by jhelsel11** [comment]
@e-lo 
Rachel's package versions:
Geopandas 0.6.3 (she had this issue with version 0.7.0 but I rolled her back to 0.6.3 because that's what I had on my end and it was working).
Fiona  1.8.13
GDAL 3.0.4
Pyproj 2.6.1.post1
Rtree  0.9.4
Shapely 1.7.0

**Comment by e-lo** [comment]
Ok I've run everything here and can't recreate the issue. I'm wondering if the issue was that the network files may have been *created* with the master version of wrangler which may have exported the coordinate system with it.  Maybe??

@jhelsel11  you can test this hypothesis (I have to sign off for the night) 

@jhelsel11 : I'd also update your environment (or create a new one) that is the same as Rachels for you to test with and go thru the notebook again to make sure it isn't a windows/mac thing (I'm on a mac)

**Comment by jhelsel11** [comment]
@e-lo, I created a new environment where I installed lasso and network_wrangler from master (the basic lasso instructions). The versions for the geopandas dependencies all matched what was on Rachel's system.

I was able to run the project card creation with no issue, though there were crs _warngings_ as you can see in the attached pdf of the output. 

Should I just ask Rachel to reinstall lasso in a new environment?
[lasso project card.pdf](https://github.com/wsp-sag/Lasso/files/4732389/lasso.project.card.pdf)

**Comment by RachelWikenMC** [comment]
I had Dennis attempt a fresh install using the directions on github and he was able to install Lasso and run the quickstart project card notebook without error. 

His comments on that step 
1)	When I first tried to install the folium package, I got an error saying folium was not found at that location.  To install folium, I first had to add “conda config --add channels conda-forge” to the Anaconda prompt
2)	Rachel's email said to install the develop branch, not the main.  But the “From Clone” instructions look like they are installing the master branch.  I think the instructions “git clone https://github.com/wsp-sag/Lasso” install the master branch.  So I just installed the master (I think installing the develop branch would have to be “git clone -b develop https://github.com/wsp-sag/Lasso” (looks like we need clarification what branch to be on here, John directed me to the develop branch – RW)

I then had him take the full network and my test log file that was causing issues for me and run the project card creation notebook again. He got past the CRS issues but hit another error. See attached 
[Dennis _error test1.pdf](https://github.com/wsp-sag/Lasso/files/4732635/Dennis._error.test1.pdf)

Helpful? more confusing? not sure. but doesn't appear the CRS issues are universal to new installs on met council hardware 

let me know what my next trouble shooting step is, if i should fully reinstall

**Comment by i-am-sijia** [comment]
@RachelWikenMC  The error Dennis is getting should be solved by commit https://github.com/wsp-sag/Lasso/commit/d706831c893fa900e7f3df52d02113e8e0bc516e in develop branch.  We have not pulled all the latest commits from develop to master yet, so as John have suggested, you can install from the develop branch for now.  Eventually you would only install from master, when we merge develop into master.

**Comment by e-lo** [comment]
@jhelsel11 - it sounds like you all are past this issue? can this be closed?

**Comment by e-lo** [comment]
Per discussions with @RachelWikenMC  today it sounds like this isn't an issue anymore so I am closing.

**Comment by RachelWikenMC** [comment]
It appears this issue was not related to install but a corrupted notebook. I had not made any intentional edits to the notebook, so not sure what the issue was, but deleting the cloned repo and bringing a fresh copy fixed my problems.
